cache:
  directories:
  - node_modules

jobs:
  include:

  - stage: lint
    language: node_js
    node_js: lts/*
    script: npm run lint

  - stage: test
    language: node_js
    node_js:
    - 10
    - 12
    - 14
    - lts/*
    os:
    - windows
    - linux
    - osx
    script: npm test
    after_success: npm run coveralls

  - stage: build
    language: node_js
    node_js: lts/*
    script: npm run build

  - stage: npm release
    language: node_js
    node_js: lts/*
    script: echo "Deploying to npm..."
    deploy:
      provider: npm
      email: simon@nilsson.ml
      api_key: "$NPM_API_KEY"
      on:
        tags: true

  - stage: github release
    language: minimal
    script: echo "Deploying to github..."
    deploy:
      provider: releases
      api_key: "$GITHUB_API_KEY"
      file_glob: true
      file:
        - "build/ios-uploader-*"
      skip_cleanup: true
      on:
        tags: true
