language: node_js
node_js:
  - 10
  - 12
  - 14
  - lts/*
os:
  - windows
  - linux
  - osx
stages:
  - Lint
  - Test
  - name: Github Release
    if: tag IS present
  - name: NPM Release
    if: tag IS present
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: Lint
      os: linux
      node_js: lts/*
      script: npm run lint

    - stage: Test
      script: npm test
      after_success: npm run coveralls

    - stage: Github Release
      os: linux
      node_js: lts/*
      script: npm run build && echo "Deploying to github..."
      deploy:
        provider: releases
        api_key: "$GITHUB_API_KEY"
        file_glob: true
        skip_cleanup: true
        cleanup: false
        file:
          - "build/ios-uploader-*"
        on:
          branch: master
          tags: true

    - stage: NPM Release
      os: linux
      node_js: lts/*
      script: echo "Deploying to npm..."
      deploy:
        provider: npm
        email: simon@nilsson.ml
        api_key: "$NPM_API_KEY"
        on:
          branch: master
          tags: true

